version: "0.2"
language: en
words:
  - absolutize
  - absolutized
  - absolutizes
  - arktype
  - begincolumn
  - beginline
  - buildid
  - compoundassign
  - covmap
  - defu
  - difftime
  - doublestar
  - elseBlock
  - elseExpr
  - elseifs
  - endcolumn
  - fmod
  - foreachi
  - frexp
  - getmetatable
  - getn
  - gmatch
  - gsub
  - highlightjs
  - indexexpr
  - instrumentable
  - instrumenter
  - interp
  - interpolatedstring
  - interpstring
  - ipairs
  - ldexp
  - lhsOperand
  - localfunction
  - materializer
  - maxn
  - misresolution
  - modf
  - newproxy
  - ocale
  - pcall
  - randomseed
  - rawequal
  - rawget
  - rawlen
  - rawset
  - rbxl
  - rbxlx
  - rhsOperand
  - rojo
  - setmetatable
  - statfunction
  - statlocalfunction
  - thenBlock
  - thenExpr
  - typealias
  - typeassertion
  - typefunction
  - uncompiled
  - unmappable
  - unstub
  - upgraders
  - vararg
  - varargs
  - writeback
  - xpcall
