version: "0.2"
language: en
words:
  - absolutize
  - absolutized
  - absolutizes
  - arktype
  - begincolumn
  - beginline
  - compoundassign
  - covmap
  - defu
  - doublestar
  - elseBlock
  - elseExpr
  - elseifs
  - endcolumn
  - highlightjs
  - indexexpr
  - instrumentable
  - instrumenter
  - interp
  - interpolatedstring
  - interpstring
  - lhsOperand
  - localfunction
  - materializer
  - misresolution
  - ocale
  - rbxl
  - rbxlx
  - rhsOperand
  - rojo
  - statfunction
  - statlocalfunction
  - thenBlock
  - thenExpr
  - typealias
  - typeassertion
  - typefunction
  - unmappable
  - unstub
  - vararg
  - varargs
  - writeback
