import { fromAny } from "@total-typescript/shoehorn";

import { vol } from "memfs";
import { describe, expect, it, onTestFinished, vi } from "vitest";

import { ConfigError } from "./errors.ts";
import type { ResolvedProjectConfig } from "./projects.ts";
import type { ProjectTestConfig, ResolvedConfig } from "./schema.ts";
import { DEFAULT_CONFIG } from "./schema.ts";
import {
	assertStubCollisionRule,
	generateProjectConfigs,
	serializeToLuau,
	syncStubsToShadowDirectory,
} from "./stubs.ts";

function makeResolvedProject(
	overrides: Partial<ResolvedProjectConfig> = {},
): ResolvedProjectConfig {
	const config: ResolvedConfig = {
		...DEFAULT_CONFIG,
		rootDir: "/root",
	};
	return {
		config,
		displayName: "client",
		include: ["src/client/**/*.spec.ts"],
		outDir: "out/client",
		projects: ["ReplicatedStorage/client"],
		rojoMounts: [{ dataModelPath: "ReplicatedStorage/client", fsPath: "out/client" }],
		testMatch: ["**/*.spec"],
		...overrides,
	};
}

vi.mock(import("node:fs"), async () => {
	const memfs = await vi.importActual<typeof import("memfs")>("memfs");
	return fromAny({ ...memfs.fs, default: memfs.fs });
});

function minimalConfig(overrides: Partial<ProjectTestConfig> = {}): ProjectTestConfig {
	return {
		displayName: "test",
		include: ["src/**"],
		...overrides,
	};
}

describe(serializeToLuau, () => {
	it("should serialize displayName string", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ displayName: "client" }));

		expect(result).toContain('\tdisplayName = "client",');
	});

	it("should serialize displayName object with name and color", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				displayName: { name: "client", color: "blue" },
			}),
		);

		expect(result).toContain('\tdisplayName = { name = "client", color = "blue" },');
	});

	it("should serialize testMatch array with stripped extensions", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				testMatch: ["**/*.spec.ts", "**/*.test.tsx", "**/*.spec.luau"],
			}),
		);

		expect(result).toContain('\ttestMatch = { "**/*.spec", "**/*.test", "**/*.spec" },');
	});

	it("should serialize boolean fields", () => {
		expect.assertions(2);

		const result = serializeToLuau(minimalConfig({ clearMocks: true, restoreMocks: false }));

		expect(result).toContain("\tclearMocks = true,");
		expect(result).toContain("\trestoreMocks = false,");
	});

	it("should serialize number fields", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ slowTestThreshold: 5 }));

		expect(result).toContain("\tslowTestThreshold = 5,");
	});

	it("should serialize snapshotFormat nested object", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				snapshotFormat: { indent: 4, printBasicPrototype: false },
			}),
		);

		expect(result).toContain("\tsnapshotFormat = { indent = 4, printBasicPrototype = false },");
	});

	it("should skip include and exclude fields", () => {
		expect.assertions(2);

		const result = serializeToLuau(
			minimalConfig({
				exclude: ["node_modules/**"],
				include: ["src/**"],
			}),
		);

		expect(result).not.toContain("include");
		expect(result).not.toContain("exclude");
	});

	it("should skip undefined values", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ setupFiles: undefined }));

		expect(result).not.toContain("setupFiles");
	});

	it("should escape quotes in string values", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ testEnvironment: 'env"with"quotes' }));

		expect(result).toContain('\ttestEnvironment = "env\\"with\\"quotes",');
	});

	it("should escape newlines, carriage returns, and tabs in string values", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({ testEnvironment: "line1\nline2\rline3\twith-tab" }),
		);

		expect(result).toContain('\ttestEnvironment = "line1\\nline2\\rline3\\twith-tab",');
	});

	it("should add auto-generated header comment", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig());

		expect(result).toStartWith("-- Auto-generated by jest-roblox (do not edit)\n");
	});

	it("should serialize all project config fields", () => {
		expect.assertions(4);

		const config: ProjectTestConfig = {
			clearMocks: true,
			displayName: "client",
			include: ["src/client/**/*.spec.ts"],
			setupFiles: ["ReplicatedStorage/setup"],
			testMatch: ["**/*.spec.ts"],
			testTimeout: 5000,
		};
		const result = serializeToLuau(config);

		expect(result).toContain("clearMocks = true");
		expect(result).toContain("testTimeout = 5000");
		expect(result).toContain('setupFiles = { "ReplicatedStorage/setup" }');
		expect(result).toContain("testMatch");
	});

	it("should serialize null values via String fallback", () => {
		expect.assertions(1);

		// serializeLuauValue falls through to String(null) → "null" for
		// unrecognized types. This is intentional fallback behavior.
		const config: ProjectTestConfig = fromAny({
			displayName: "test",
			include: ["src/**"],
			testTimeout: null,
		});
		const result = serializeToLuau(config);

		expect(result).toContain("testTimeout = null,");
	});
});

describe(generateProjectConfigs, () => {
	it("should write config file to specified path", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		generateProjectConfigs([
			{
				config: minimalConfig({ displayName: "client" }),
				outputPath: "/out/client.config.luau",
			},
		]);

		const content = vol.readFileSync("/out/client.config.luau", "utf8");

		expect(content).toContain('\tdisplayName = "client",');
	});

	it("should create parent directories if they don't exist", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		generateProjectConfigs([
			{
				config: minimalConfig(),
				outputPath: "/deep/nested/dir/test.config.luau",
			},
		]);

		expect(vol.existsSync("/deep/nested/dir/test.config.luau")).toBeTrue();
	});

	it("should skip writing when jest.config.luau already exists at output directory", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/out/client", { recursive: true });
		vol.writeFileSync("/out/client/jest.config.luau", "return {}");

		generateProjectConfigs([
			{
				config: minimalConfig({ displayName: "client" }),
				outputPath: "/out/client/jest.config.lua",
			},
		]);

		expect(vol.existsSync("/out/client/jest.config.lua")).toBeFalse();
	});

	it("should write config files for multiple roots", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		generateProjectConfigs([
			{
				config: { displayName: "client", include: [], testMatch: ["**/*.spec"] },
				outputPath: "/out/client/jest.config.lua",
			},
			{
				config: { displayName: "server", include: [], testMatch: ["**/*.spec"] },
				outputPath: "/out/server/jest.config.lua",
			},
		]);

		expect(vol.existsSync("/out/client/jest.config.lua")).toBeTrue();
		expect(vol.existsSync("/out/server/jest.config.lua")).toBeTrue();
	});

	it("should write multiple project configs", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		generateProjectConfigs([
			{
				config: minimalConfig({ displayName: "client" }),
				outputPath: "/out/client.config.luau",
			},
			{
				config: minimalConfig({ displayName: "server" }),
				outputPath: "/out/server.config.luau",
			},
		]);

		const client = vol.readFileSync("/out/client.config.luau", "utf8");
		const server = vol.readFileSync("/out/server.config.luau", "utf8");

		expect(client).toContain('\tdisplayName = "client",');
		expect(server).toContain('\tdisplayName = "server",');
	});
});

describe(syncStubsToShadowDirectory, () => {
	it("should copy stub files from original dirs to shadow dir", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/out/client", { recursive: true });
		vol.writeFileSync("/root/out/client/jest.config.lua", "-- stub");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.readFileSync("/shadow/out/client/jest.config.lua", "utf8")).toBe("-- stub");
	});

	it("should return true when stub is new", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/out/client", { recursive: true });
		vol.writeFileSync("/root/out/client/jest.config.lua", "-- stub");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeTrue();
	});

	it("should return true when stub content changed", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/out/client", { recursive: true });
		vol.writeFileSync("/root/out/client/jest.config.lua", "-- updated");
		vol.mkdirSync("/shadow/out/client", { recursive: true });
		vol.writeFileSync("/shadow/out/client/jest.config.lua", "-- old");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeTrue();
	});

	it("should return false when stub content identical", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/out/client", { recursive: true });
		vol.writeFileSync("/root/out/client/jest.config.lua", "-- same");
		vol.mkdirSync("/shadow/out/client", { recursive: true });
		vol.writeFileSync("/shadow/out/client/jest.config.lua", "-- same");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeFalse();
	});

	it("should skip projects with empty rojoMounts", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		const projects = [makeResolvedProject({ outDir: undefined, rojoMounts: [] })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeFalse();
	});

	it("should create directories in shadow dir as needed", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/out/deep/nested", { recursive: true });
		vol.writeFileSync("/root/out/deep/nested/jest.config.lua", "-- stub");

		const projects = [
			makeResolvedProject({
				outDir: "out/deep/nested",
				rojoMounts: [
					{ dataModelPath: "ReplicatedStorage/deep", fsPath: "out/deep/nested" },
				],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.existsSync("/shadow/out/deep/nested/jest.config.lua")).toBeTrue();
	});

	it("should delete orphaned shadow stubs not in current projects and return true", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		// Orphaned stub in shadow dir (no matching project)
		vol.mkdirSync("/shadow/out/removed", { recursive: true });
		vol.writeFileSync("/shadow/out/removed/jest.config.lua", "-- orphan");

		const projects: Array<ResolvedProjectConfig> = [];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeTrue();
		expect(vol.existsSync("/shadow/out/removed/jest.config.lua")).toBeFalse();
	});

	it("should throw when mount fsPath is an absolute path", () => {
		expect.assertions(1);

		const projects = [
			makeResolvedProject({
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/evil", fsPath: "/tmp/evil" }],
			}),
		];

		expect(() => syncStubsToShadowDirectory(projects, "/root", "/shadow")).toThrow(
			"mount fsPath must be relative",
		);
	});

	it("should throw when mount fsPath escapes rootDirectory via parent segments", () => {
		expect.assertions(1);

		const projects = [
			makeResolvedProject({
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/outside", fsPath: "../outside" }],
			}),
		];

		expect(() => syncStubsToShadowDirectory(projects, "/root", "/shadow")).toThrow(
			"mount fsPath escapes root directory",
		);
	});

	it("should clean up empty parent directories after orphan removal", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/shadow/out/removed/deep", { recursive: true });
		vol.writeFileSync("/shadow/out/removed/deep/jest.config.lua", "-- orphan");

		const projects: Array<ResolvedProjectConfig> = [];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.existsSync("/shadow/out/removed/deep")).toBeFalse();
		expect(vol.existsSync("/shadow/out/removed")).toBeFalse();
	});

	it("should return false when no orphans and no changes", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		// No stubs anywhere, no mounts tracked
		const projects = [makeResolvedProject({ outDir: undefined, rojoMounts: [] })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeFalse();
	});

	it("should not remove parent when it still contains other files", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/shadow/out/mixed", { recursive: true });
		vol.writeFileSync("/shadow/out/mixed/jest.config.lua", "-- orphan");
		vol.writeFileSync("/shadow/out/mixed/other-file.txt", "keep me");

		const projects: Array<ResolvedProjectConfig> = [];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.existsSync("/shadow/out/mixed/jest.config.lua")).toBeFalse();
		expect(vol.existsSync("/shadow/out/mixed/other-file.txt")).toBeTrue();
	});

	it("should ignore non-config files in shadow directory", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/shadow/out/project", { recursive: true });
		vol.writeFileSync("/shadow/out/project/not-a-config.lua", "-- not a config");

		const projects: Array<ResolvedProjectConfig> = [];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeFalse();
	});

	it("should skip project when source stub does not exist", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		// outDir exists but jest.config.lua does not
		vol.mkdirSync("/root/out/client", { recursive: true });

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const result = syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(result).toBeFalse();
	});

	it("should copy stubs from every mount of a multi-mount project", () => {
		expect.assertions(3);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		vol.mkdirSync("/root/src/Shared", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.lua", "-- stub");
		vol.writeFileSync("/root/src/Server/jest.config.lua", "-- stub");
		vol.writeFileSync("/root/src/Shared/jest.config.lua", "-- stub");

		const projects = [
			makeResolvedProject({
				outDir: undefined,
				rojoMounts: [
					{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
					{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
					{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "src/Shared" },
				],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.existsSync("/shadow/src/Client/jest.config.lua")).toBeTrue();
		expect(vol.existsSync("/shadow/src/Server/jest.config.lua")).toBeTrue();
		expect(vol.existsSync("/shadow/src/Shared/jest.config.lua")).toBeTrue();
	});

	it("should remove shadow stub when its mount is dropped between runs", () => {
		expect.assertions(2);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.lua", "-- stub");
		vol.mkdirSync("/shadow/src/Client", { recursive: true });
		vol.writeFileSync("/shadow/src/Client/jest.config.lua", "-- stub");
		// Stale shadow stub for a mount that no longer exists.
		vol.mkdirSync("/shadow/src/Removed", { recursive: true });
		vol.writeFileSync("/shadow/src/Removed/jest.config.lua", "-- stale");

		const projects = [
			makeResolvedProject({
				outDir: undefined,
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" }],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", "/shadow");

		expect(vol.existsSync("/shadow/src/Client/jest.config.lua")).toBeTrue();
		expect(vol.existsSync("/shadow/src/Removed/jest.config.lua")).toBeFalse();
	});
});

describe(assertStubCollisionRule, () => {
	it("should accept when no mount has a user-authored config", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root");
		}).not.toThrow();
	});

	it("should accept when every mount has a user jest.config.luau", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.luau", "return {}");
		vol.writeFileSync("/root/src/Server/jest.config.luau", "return {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root");
		}).not.toThrow();
	});

	it("should accept when every mount has a user jest.config.lua (non-generated)", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.lua", "-- user wrote this\nreturn {}");
		vol.writeFileSync("/root/src/Server/jest.config.lua", "-- user wrote this\nreturn {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root");
		}).not.toThrow();
	});

	it("should accept when mixed user extensions cover every mount", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.luau", "return {}");
		vol.writeFileSync("/root/src/Server/jest.config.lua", "-- user-authored\nreturn {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root");
		}).not.toThrow();
	});

	it("should throw when only some mounts have a user config", () => {
		expect.assertions(3);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.luau", "return {}");

		const project = makeResolvedProject({
			displayName: "partial",
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		let caught: ConfigError | undefined;
		try {
			assertStubCollisionRule(project, "/root");
		} catch (err) {
			caught = err as ConfigError;
		}

		expect(caught).toBeInstanceOf(ConfigError);
		expect(caught?.message).toContain("src/Client");
		expect(caught?.message).toContain("src/Server");
	});

	it("should ignore our own generated .lua when counting user configs", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.mkdirSync("/root/src/Server", { recursive: true });
		// Our generated stub in one mount should not count as a user config.
		vol.writeFileSync(
			"/root/src/Client/jest.config.lua",
			"-- Auto-generated by jest-roblox (do not edit)\nreturn {}",
		);

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		// Both mounts effectively have no user config, so no throw.
		expect(() => {
			assertStubCollisionRule(project, "/root");
		}).not.toThrow();
	});
});

describe("generateProjectConfigs with multi-mount projects", () => {
	it("should write identical stubs at every mount's outputPath", () => {
		expect.assertions(3);

		onTestFinished(() => {
			vol.reset();
		});

		const stubConfig: ProjectTestConfig = {
			displayName: "friends",
			include: [],
			testMatch: ["**/*.spec"],
		};

		generateProjectConfigs([
			{ config: stubConfig, outputPath: "/root/src/Client/jest.config.lua" },
			{ config: stubConfig, outputPath: "/root/src/Server/jest.config.lua" },
			{ config: stubConfig, outputPath: "/root/src/Shared/jest.config.lua" },
		]);

		const clientContent = vol.readFileSync("/root/src/Client/jest.config.lua", "utf8");
		const serverContent = vol.readFileSync("/root/src/Server/jest.config.lua", "utf8");
		const sharedContent = vol.readFileSync("/root/src/Shared/jest.config.lua", "utf8");

		expect(clientContent).toBe(serverContent);
		expect(serverContent).toBe(sharedContent);
		expect(clientContent).toContain('\tdisplayName = "friends",');
	});

	it("should skip writing when user's jest.config.lua exists at target", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.writeFileSync("/root/src/Client/jest.config.lua", "-- user-authored\nreturn {}");

		generateProjectConfigs([
			{
				config: { displayName: "friends", include: [], testMatch: ["**/*.spec"] },
				outputPath: "/root/src/Client/jest.config.lua",
			},
		]);

		// User's file preserved, not overwritten.
		expect(vol.readFileSync("/root/src/Client/jest.config.lua", "utf8")).toBe(
			"-- user-authored\nreturn {}",
		);
	});

	it("should overwrite our own previously-generated stub on re-gen", () => {
		expect.assertions(1);

		onTestFinished(() => {
			vol.reset();
		});

		vol.mkdirSync("/root/src/Client", { recursive: true });
		vol.writeFileSync(
			"/root/src/Client/jest.config.lua",
			"-- Auto-generated by jest-roblox (do not edit)\n-- old content\n",
		);

		generateProjectConfigs([
			{
				config: { displayName: "updated", include: [], testMatch: ["**/*.spec"] },
				outputPath: "/root/src/Client/jest.config.lua",
			},
		]);

		expect(vol.readFileSync("/root/src/Client/jest.config.lua", "utf8")).toContain(
			'\tdisplayName = "updated",',
		);
	});
});
