import { Buffer } from "node:buffer";
import fs from "node:fs";
import path from "node:path";

import { stripTsExtension } from "../utils/extensions.ts";
import { ConfigError } from "./errors.ts";
import type { ResolvedProjectConfig } from "./projects.ts";
import type { ProjectTestConfig, ResolvedConfig } from "./schema.ts";
import { PROJECT_TEST_KEYS } from "./schema.ts";

const HEADER = "-- Auto-generated by jest-roblox (do not edit)\n";

export const STUB_FILENAME = "jest.config.luau";

const LEGACY_LUA_FILENAME = "jest.config.lua";

const SKIP_FIELDS: ReadonlySet<string> = new Set(["exclude", "include"]);

export function serializeToLuau(config: ProjectTestConfig): string {
	let output = `${HEADER}return {\n`;

	for (const [key, value] of Object.entries(config)) {
		if (SKIP_FIELDS.has(key)) {
			continue;
		}

		if (value === undefined) {
			continue;
		}

		let serialized: string;
		if (key === "testMatch" && Array.isArray(value)) {
			const stripped = (value as Array<string>).map((pattern) => stripTsExtension(pattern));
			serialized = serializeLuauValue(stripped, "\t");
		} else {
			serialized = serializeLuauValue(value, "\t");
		}

		output += `\t${key} = ${serialized},\n`;
	}

	output += "}\n";
	return output;
}

export function generateProjectConfigs(
	projects: Array<{ config: ProjectTestConfig; outputPath: string }>,
): void {
	for (const project of projects) {
		const directory = path.dirname(project.outputPath);
		if (hasUserAuthoredConfig(directory)) {
			continue;
		}

		const content = serializeToLuau(project.config);
		fs.mkdirSync(directory, { recursive: true });
		fs.writeFileSync(project.outputPath, content, "utf8");

		if (path.basename(project.outputPath) === STUB_FILENAME) {
			removeLegacyGeneratedStub(directory);
		}
	}
}

// All five are valid `ProjectTestConfig` members but the project-level
// values are unwanted in the stub: `outDir`/`root` are reconstructed
// per-mount by `generateProjectStubs`, and `displayName`/`include`/`exclude`
// are overwritten by the spread in `generateProjectStubs` (with
// `include`/`exclude` further dropped by `serializeToLuau`'s `SKIP_FIELDS`).
// Strip them upstream to keep `buildStubConfig`'s output tight.
const STUB_SKIP_KEYS: ReadonlySet<string> = new Set([
	"displayName",
	"exclude",
	"include",
	"outDir",
	"root",
]);

/**
 * Refuse to let any downstream write land outside `rootDirectory`. Mount
 * fsPaths originate from the rojo tree and `resolveNestedProjects` can emit
 * values with `..` segments (nested projects relocate paths); combined with
 * `path.resolve` on Windows, a permissive fsPath could send stub writes to
 * `D:\outside\...`. Guard at every write-site.
 */
export function assertMountContained(
	project: ResolvedProjectConfig,
	fsPath: string,
	rootDirectory: string,
): void {
	if (path.isAbsolute(fsPath)) {
		throw new Error(
			`Project "${project.displayName}" mount fsPath must be relative, got: ${fsPath}`,
		);
	}

	const rootResolved = path.resolve(rootDirectory);
	const mountResolved = path.resolve(rootDirectory, fsPath);
	if (mountResolved !== rootResolved && !mountResolved.startsWith(rootResolved + path.sep)) {
		throw new Error(
			`Project "${project.displayName}" mount fsPath escapes root directory: ${fsPath}`,
		);
	}
}

/**
 * For a multi-mount project, the stubs-per-mount rule requires that a
 * user-authored config at any tracked FS path must appear at every tracked
 * FS path (or none). Throws `ConfigError` when the project has partial
 * coverage — some mounts have a user config and others don't.
 */
export function assertStubCollisionRule(
	project: ResolvedProjectConfig,
	rootDirectory: string,
): void {
	const withUser: Array<string> = [];
	const withoutUser: Array<string> = [];

	for (const mount of project.rojoMounts) {
		assertMountContained(project, mount.fsPath, rootDirectory);

		const absolute = path.resolve(rootDirectory, mount.fsPath);
		if (hasUserAuthoredConfig(absolute)) {
			withUser.push(mount.fsPath);
		} else {
			withoutUser.push(mount.fsPath);
		}
	}

	if (withUser.length === 0 || withoutUser.length === 0) {
		return;
	}

	const withUserList = withUser.join(", ");
	const withoutUserList = withoutUser.join(", ");
	throw new ConfigError(
		`Project "${project.displayName}": user-authored jest config present at some mounts but not others.\n\n` +
			`With user config: ${withUserList}\n` +
			`Without user config: ${withoutUserList}\n\n` +
			"For multi-mount projects, either every tracked mount must have a user config, or none.",
	);
}

/**
 * `assertStubCollisionRule` always scans the package source tree (its job is
 * partial-coverage detection); only the write target moves when `outputRoot`
 * is provided.
 */
export function generateProjectStubs(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
	outputRoot?: string,
): void {
	const writeRoot = outputRoot ?? rootDirectory;
	const entries: Array<{ config: ProjectTestConfig; outputPath: string }> = [];

	for (const project of projects) {
		assertStubCollisionRule(project, rootDirectory);

		const stubConfig: ProjectTestConfig = {
			...buildStubConfig(project.config),
			displayName: project.displayName,
			include: [],
			testMatch: project.testMatch,
		};

		for (const mount of project.rojoMounts) {
			assertMountContained(project, mount.fsPath, writeRoot);
			const outputPath = path.resolve(writeRoot, mount.fsPath, STUB_FILENAME);
			entries.push({ config: stubConfig, outputPath });
		}
	}

	generateProjectConfigs(entries);
}

export function syncStubsToShadowDirectory(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
	shadowDirectory: string,
): boolean {
	let changed = false;
	const expectedPaths = new Set<string>();

	for (const project of projects) {
		for (const mount of project.rojoMounts) {
			const result = syncMountStub(project, mount.fsPath, rootDirectory, shadowDirectory);
			if (result.targetPath !== undefined) {
				expectedPaths.add(result.targetPath);
			}

			changed ||= result.changed;
		}
	}

	for (const existing of findShadowStubs(shadowDirectory)) {
		if (!expectedPaths.has(existing)) {
			fs.unlinkSync(existing);
			removeEmptyParents(path.dirname(existing), shadowDirectory);
			changed = true;
		}
	}

	return changed;
}

function hasUserAuthoredConfig(directoryPath: string): boolean {
	// `.luau` may be either our generated stub or a user-authored config —
	// only the HEADER comment distinguishes them. Only user-authored is
	// protected from overwrite.
	const luauPath = path.join(directoryPath, STUB_FILENAME);
	if (fs.existsSync(luauPath)) {
		const content = fs.readFileSync(luauPath, "utf8");
		if (!content.startsWith(HEADER)) {
			return true;
		}
	}

	// Legacy: user-authored `.lua` (HEADER absent) is still respected so
	// existing user configs aren't silently overwritten after the rename.
	const luaPath = path.join(directoryPath, LEGACY_LUA_FILENAME);
	if (!fs.existsSync(luaPath)) {
		return false;
	}

	const content = fs.readFileSync(luaPath, "utf8");
	return !content.startsWith(HEADER);
}

function buildStubConfig(config: ResolvedConfig): Partial<ProjectTestConfig> {
	const result: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(config)) {
		if (PROJECT_TEST_KEYS.has(key) && !STUB_SKIP_KEYS.has(key) && value !== undefined) {
			result[key] = value;
		}
	}

	return result;
}

function syncMountStub(
	project: ResolvedProjectConfig,
	fsPath: string,
	rootDirectory: string,
	shadowDirectory: string,
): { changed: boolean; targetPath: string | undefined } {
	assertMountContained(project, fsPath, rootDirectory);

	const sourcePath = path.resolve(rootDirectory, fsPath, STUB_FILENAME);
	if (!fs.existsSync(sourcePath)) {
		return { changed: false, targetPath: undefined };
	}

	const targetPath = path.resolve(shadowDirectory, fsPath, STUB_FILENAME);
	const sourceContent = fs.readFileSync(sourcePath);

	if (fs.existsSync(targetPath)) {
		const targetContent = fs.readFileSync(targetPath);
		if (Buffer.compare(sourceContent, targetContent) === 0) {
			return { changed: false, targetPath };
		}
	}

	fs.mkdirSync(path.dirname(targetPath), { recursive: true });
	fs.copyFileSync(sourcePath, targetPath);
	return { changed: true, targetPath };
}

function findShadowStubs(directory: string): Array<string> {
	const results: Array<string> = [];
	if (!fs.existsSync(directory)) {
		return results;
	}

	const entries = fs.readdirSync(directory, { withFileTypes: true });
	for (const entry of entries) {
		const fullPath = path.resolve(directory, entry.name);
		if (entry.isDirectory()) {
			results.push(...findShadowStubs(fullPath));
		} else if (entry.name === STUB_FILENAME || entry.name === LEGACY_LUA_FILENAME) {
			results.push(fullPath);
		}
	}

	return results;
}

function removeEmptyParents(directory: string, stopAt: string): void {
	const resolved = path.resolve(directory);
	const resolvedStop = path.resolve(stopAt);
	if (resolved === resolvedStop || !resolved.startsWith(resolvedStop)) {
		return;
	}

	try {
		const entries = fs.readdirSync(resolved);
		if (entries.length === 0) {
			fs.rmdirSync(resolved);
			removeEmptyParents(path.dirname(resolved), stopAt);
		}
	} catch {
		// Best-effort cleanup
	}
}

// Rojo merges `jest.config.lua` and `jest.config.luau` into the same
// ModuleScript name, so leaving an old generated `.lua` stub next to the
// new `.luau` would cause a name collision after upgrade. Caller guarantees
// (via `hasUserAuthoredConfig`) that any `.lua` present here is our own
// HEADER-prefixed stub, not a user-authored file.
function removeLegacyGeneratedStub(directoryPath: string): void {
	const legacyPath = path.join(directoryPath, LEGACY_LUA_FILENAME);
	if (fs.existsSync(legacyPath)) {
		fs.unlinkSync(legacyPath);
	}
}

function escapeString(value: string): string {
	return value
		.replace(/\\/g, "\\\\")
		.replace(/"/g, '\\"')
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t");
}

function serializeLuauValue(value: unknown, indent: string): string {
	if (typeof value === "string") {
		return `"${escapeString(value)}"`;
	}

	if (typeof value === "boolean") {
		return value ? "true" : "false";
	}

	if (typeof value === "number") {
		return String(value);
	}

	if (Array.isArray(value)) {
		const items = value.map((item: unknown) => serializeLuauValue(item, indent));
		return `{ ${items.join(", ")} }`;
	}

	if (typeof value === "object" && value !== null) {
		const nextIndent = `${indent}\t`;
		const entries = Object.entries(value)
			.filter(([, value_]) => value_ !== undefined)
			.map(([key, value_]) => `${key} = ${serializeLuauValue(value_, nextIndent)}`);
		return `{ ${entries.join(", ")} }`;
	}

	return String(value);
}
